### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by AnAngryBrit** [K-4U/ColorChat#2]
When using your mod I noticed that the spelling you used for colour in your mod is incorrect, I would appreciate a fix for this post haste.

**Comment by HoldYourWaffle** [comment]
Wich colors are misspelled then?

**Comment by K-4U** [comment]
Did i never close this? :P Yeah, i know, we have colour and color.. I've given it much thought of renaming the mod, but unfortunately, it's already known as "Colorchat"..
