### ISSUE TITLE
Doesn't render in 1.8?

### ISSUE THREAD

**Issue by Aetnaria** [K-4U/ColorChat#4]
Tried using the latest versions for MC 1.8 (ColorChat 0.1.6 & K4Lib 1.0.11, both released 6/30/15), everything seems to load but when I actually try to use the color command in multiplayer it states "Your color has now been set to " and nothing further, no matter which color I try. My color remains white. Using the "/color" command by itself does list off "Available colors are green, dark green, lightpurple, , yellow, gold, red, aqua, gray, blue, white, darkred, darkpurple, dark gray, , dark aqua." - all of which are in white (and yes there are two extra commas in what it prints as if it's missing two colors).
![multiplayer](https://cloud.githubusercontent.com/assets/1095416/13194620/52fecf68-d75d-11e5-9e48-31c4229e8e74.jpg)

When I try in singleplayer it states "An unknown error occurred while attempting to perform this command" (that actually appears in red).
![singleplayer](https://cloud.githubusercontent.com/assets/1095416/13194621/5807fe6c-d75d-11e5-8bc3-370969237ebd.jpg)

This is with Minecraft 1.8, MCP v9.10, FML8.0.99.99, Forge 11.14.4.1563.

**Comment by K-4U** [comment]
Do you have any other mods that mess around with commands?
The fact that it doesn't work in singleplayer is because it really searches for server only methods.

That said, try changing the config option "changeDisplayName" to true, as it should randomize the colour when you log in.

**Comment by Aetnaria** [comment]
Just tried the randomize color option (setting=2 instead of 1), but still only white shows up.

Not aware of command-changing mods, but I’ll check. My current mod list is:
airbreathercore-1.0.1.jar
AnimalsPlus-1.6.jar
ArchitectureCraft-1.2.1-mc1.8.jar
Armour Expansion - 1.0.jar
Chameleon-1.8-0.1.0.jar
cnm.jar
colorchat-1.8-0.1.6-universal.jar
csm.jar
CyanosLootableBodies-1.3.6.jar
Exotic Birds 1.8 - 1.0.3b.jar
Forge 1.8 Craftable Waypoints 1.2.1.jar
grapplemod-v6-1.8.jar
HardcoreDarkness-MC1.8-1.7.jar
ironchest-1.8-6.0.109.756-universal.jar
jei_1.8-2.14.0.139.jar
k4lib-1.8-1.0.11-universal.jar
Liquid Enchanting-1.8.0 - 2.0.jar
Lots of Food-1.9.0.jar
MrCrayfishFurnitureModv3.6(1.8).jar
OptiFine_1.8.0_HD_U_H2.jar
Ore Expansion-1.8 - 1.1.jar
reptilemod-1.8.0-3.1.0-26.jar
StorageDrawers-1.8-2.1.9.jar
ultimate_unicorn_mod-1.8-1.4.2.jar
WIT-1.8-1.0.0-6.jar
Xaeros_Minimap_1.8.1_Forge_1.8.jar
yalsm-2.1.5.jar

**Comment by Aetnaria** [comment]
Found it. Apparently the Liquid Enchanting-1.8.0 - 2.0.jar mod ( http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2424333-liquid-enchanting-add-potion-effects-to-armor-and ) does something that interferes with chat colors - just it alongside ColorChat and K4Lib is enough to prevent name coloration.
