### ISSUE TITLE
1.7.10 version a couple issues

### ISSUE THREAD

**Issue by Gamerbolts** [K-4U/ColorChat#6]
Hi I just found your mod and wanted to add it to my server. However I came across some issues.

1. When someone changes their nick or color. They have to kill themselves for it to take affect. Even logging out of the server and back in wont work.
2. The nick and color aren't saving. Even though I have the option selected for it to save

    # Change the mode, [1]Colours can be changed by players, random on login/n[2]Colours can be changed by players, saved between logins/n[3]Only ops can change colours/n[4]Players, Ops have set colours/n[5]Groups determine colours [Default: 1]
    I:mode=2

3. I created a group and added someone in, then tried to delete it. The group would not delete. I had to remove the mod. close the server, delete the two files in the World folder and then start and stop the server add Color Chat back in and restart for the group to be deleted.

Not sure if any of these issues have been previously present but I wanted to let you know. Mainly the one where it's not saving when the user logs out.

Thanks for the help!

**Comment by K-4U** [comment]
I'm sorry for replying this late.
I've stopped supporting all of my 1.7.10 mods, as they are running on a very old codebase now.
