### ISSUE TITLE
Groups can't be deleted

### ISSUE THREAD

**Issue by Drebledore** [K-4U/ColorChat#9]
when using /group remove <name>
it gives out this unknown error. 
I tried removing the user first with /group delUser <group> <name> 
but it didn't work aswell

![ca2](https://user-images.githubusercontent.com/66674044/84585574-02c7cd80-adc6-11ea-8fc1-db58bfe7f34f.PNG)
![Capture](https://user-images.githubusercontent.com/66674044/84585575-03606400-adc6-11ea-86c6-78ee71f338ca.PNG)

**Comment by K-4U** [comment]
Hiya!
what version of the mod and minecraft are you running?

**Comment by Drebledore** [comment]
Hello, it's 1.12.2-forge-14.23.5.2854
